// This file is generated by scripts/generate_wasm_abi_enums.mjs.
// Do not edit it manually.

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaylistType {
    MultivariantPlaylist = 0,
    MediaPlaylist = 1,
}

impl PlaylistType {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::MultivariantPlaylist,
            1 => Self::MediaPlaylist,
            _ => Self::MultivariantPlaylist,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OtherErrorCode {
    NoSupportedVariant = 0,
    UnfoundLockedVariant = 1,
    MediaSourceAttachmentError = 2,
    Unknown = 3,
}

impl OtherErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoSupportedVariant,
            1 => Self::UnfoundLockedVariant,
            2 => Self::MediaSourceAttachmentError,
            3 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SourceBufferCreationErrorCode {
    AlreadyCreatedWithSameType = 0,
    CantPlayType = 1,
    EmptyMimeType = 2,
    MediaSourceIsClosed = 3,
    NoMediaSourceAttached = 4,
    QuotaExceededError = 5,
    Unknown = 6,
}

impl SourceBufferCreationErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::AlreadyCreatedWithSameType,
            1 => Self::CantPlayType,
            2 => Self::EmptyMimeType,
            3 => Self::MediaSourceIsClosed,
            4 => Self::NoMediaSourceAttached,
            5 => Self::QuotaExceededError,
            6 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RequestErrorReason {
    Timeout = 0,
    Status = 1,
    Error = 2,
    Other = 3,
}

impl RequestErrorReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Timeout,
            1 => Self::Status,
            2 => Self::Error,
            3 => Self::Other,
            _ => Self::Other,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RemoveMediaSourceErrorCode {
    NoMediaSourceAttached = 0,
    UnknownError = 1,
}

impl RemoveMediaSourceErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaSourceDurationUpdateErrorCode {
    NoMediaSourceAttached = 0,
    UnknownError = 1,
}

impl MediaSourceDurationUpdateErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AttachMediaSourceErrorCode {
    UnknownError = 0,
    NoContentLoaded = 1,
}

impl AttachMediaSourceErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::UnknownError,
            1 => Self::NoContentLoaded,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RemoveBufferErrorCode {
    SourceBufferNotFound = 0,
    UnknownError = 1,
}

impl RemoveBufferErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::SourceBufferNotFound,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EndOfStreamErrorCode {
    NoMediaSourceAttached = 0,
    UnknownError = 1,
}

impl EndOfStreamErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MultivariantPlaylistParsingErrorCode {
    MissingExtM3uHeader = 0,
    MultivariantPlaylistWithoutVariant = 1,
    MissingUriLineAfterVariant = 2,
    UnableToReadVariantUri = 3,
    VariantMissingBandwidth = 4,
    InvalidValue = 5,
    MediaTagMissingType = 6,
    MediaTagMissingName = 7,
    MediaTagMissingGroupId = 8,
    UnableToReadLine = 9,
    Unknown = 10,
}

impl MultivariantPlaylistParsingErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::MissingExtM3uHeader,
            1 => Self::MultivariantPlaylistWithoutVariant,
            2 => Self::MissingUriLineAfterVariant,
            3 => Self::UnableToReadVariantUri,
            4 => Self::VariantMissingBandwidth,
            5 => Self::InvalidValue,
            6 => Self::MediaTagMissingType,
            7 => Self::MediaTagMissingName,
            8 => Self::MediaTagMissingGroupId,
            9 => Self::UnableToReadLine,
            10 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaPlaylistParsingErrorCode {
    UnparsableExtInf = 0,
    UriMissingInMap = 1,
    MissingTargetDuration = 2,
    UriWithoutExtInf = 3,
    UnparsableByteRange = 4,
    Unknown = 5,
}

impl MediaPlaylistParsingErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::UnparsableExtInf,
            1 => Self::UriMissingInMap,
            2 => Self::MissingTargetDuration,
            3 => Self::UriWithoutExtInf,
            4 => Self::UnparsableByteRange,
            5 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AddSourceBufferErrorCode {
    NoMediaSourceAttached = 0,
    MediaSourceIsClosed = 1,
    QuotaExceededError = 2,
    TypeNotSupportedError = 3,
    EmptyMimeType = 4,
    UnknownError = 5,
}

impl AddSourceBufferErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::MediaSourceIsClosed,
            2 => Self::QuotaExceededError,
            3 => Self::TypeNotSupportedError,
            4 => Self::EmptyMimeType,
            5 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SegmentParsingErrorCode {
    NoResource = 0,
    NoSourceBuffer = 1,
    TransmuxerError = 2,
    UnknownError = 3,
}

impl SegmentParsingErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoResource,
            1 => Self::NoSourceBuffer,
            2 => Self::TransmuxerError,
            3 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PushedSegmentErrorCode {
    BufferFull = 0,
    UnknownError = 1,
}

impl PushedSegmentErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::BufferFull,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaybackObservationReason {
    Init = 0,
    Seeked = 1,
    Seeking = 2,
    Ended = 3,
    ReadyStateChanged = 4,
    RegularInterval = 5,
    Error = 6,
}

impl PlaybackObservationReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Init,
            1 => Self::Seeked,
            2 => Self::Seeking,
            3 => Self::Ended,
            4 => Self::ReadyStateChanged,
            5 => Self::RegularInterval,
            6 => Self::Error,
            _ => Self::Error,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TimerReason {
    MediaPlaylistRefresh = 0,
    RetryRequest = 1,
}

impl TimerReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::MediaPlaylistRefresh,
            1 => Self::RetryRequest,
            _ => Self::MediaPlaylistRefresh,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LogLevel {
    Error = 0,
    Warn = 1,
    Info = 2,
    Debug = 3,
}

impl LogLevel {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Error,
            1 => Self::Warn,
            2 => Self::Info,
            3 => Self::Debug,
            _ => Self::Error,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaType {
    Audio = 0,
    Video = 1,
}

impl MediaType {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Audio,
            1 => Self::Video,
            _ => Self::Audio,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaylistNature {
    Event = 0,
    VoD = 1,
    Live = 2,
    Unknown = 3,
}

impl PlaylistNature {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Event,
            1 => Self::VoD,
            2 => Self::Live,
            3 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaSourceReadyState {
    Closed = 0,
    Ended = 1,
    Open = 2,
}

impl MediaSourceReadyState {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Closed,
            1 => Self::Ended,
            2 => Self::Open,
            _ => Self::Closed,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StartingPositionType {
    Absolute = 0,
    FromBeginning = 1,
    FromEnd = 2,
}

impl StartingPositionType {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Absolute,
            1 => Self::FromBeginning,
            2 => Self::FromEnd,
            _ => Self::Absolute,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaybackTickReason {
    Init = 0,
    RegularInterval = 1,
    Seeking = 2,
    Seeked = 3,
    LoadedData = 4,
    LoadedMetadata = 5,
    CanPlay = 6,
    CanPlayThrough = 7,
    Ended = 8,
    Pause = 9,
    Play = 10,
    RateChange = 11,
    Stalled = 12,
}

impl PlaybackTickReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Init,
            1 => Self::RegularInterval,
            2 => Self::Seeking,
            3 => Self::Seeked,
            4 => Self::LoadedData,
            5 => Self::LoadedMetadata,
            6 => Self::CanPlay,
            7 => Self::CanPlayThrough,
            8 => Self::Ended,
            9 => Self::Pause,
            10 => Self::Play,
            11 => Self::RateChange,
            12 => Self::Stalled,
            _ => Self::Init,
        }
    }
}
