// This file is generated by scripts/generate_wasm_abi_enums.mjs.
// Do not edit it manually.

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaylistType {
    MultivariantPlaylist = 0,
    MediaPlaylist = 1,
}

impl PlaylistType {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::MultivariantPlaylist,
            1 => Self::MediaPlaylist,
            _ => Self::MultivariantPlaylist,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OtherErrorCode {
    NoSupportedVariant = 0,
    UnfoundLockedVariant = 1,
    MediaSourceAttachmentError = 2,
    Unknown = 3,
}

impl OtherErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoSupportedVariant,
            1 => Self::UnfoundLockedVariant,
            2 => Self::MediaSourceAttachmentError,
            3 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SourceBufferCreationErrorCode {
    AlreadyCreatedWithSameType = 0,
    CantPlayType = 1,
    EmptyMimeType = 2,
    MediaSourceIsClosed = 3,
    NoMediaSourceAttached = 4,
    QuotaExceededError = 5,
    Unknown = 6,
}

impl SourceBufferCreationErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::AlreadyCreatedWithSameType,
            1 => Self::CantPlayType,
            2 => Self::EmptyMimeType,
            3 => Self::MediaSourceIsClosed,
            4 => Self::NoMediaSourceAttached,
            5 => Self::QuotaExceededError,
            6 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RequestErrorReason {
    Timeout = 0,
    Status = 1,
    Error = 2,
    Other = 3,
}

impl RequestErrorReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Timeout,
            1 => Self::Status,
            2 => Self::Error,
            3 => Self::Other,
            _ => Self::Other,
        }
    }
}

/// Errors that can arise when attempting to remove a MediaSource previously attached
/// to a media element.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RemoveMediaSourceErrorCode {
    /// Could not remove MediaSource from the media element because this `WaspHlsPlayer`
    /// had no MediaSource attached to its media element.
    NoMediaSourceAttached = 0,
    /// Could not remove MediaSource from the media element because of an unknown error.
    UnknownError = 1,
}

impl RemoveMediaSourceErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

/// Errors that can arise when attempting to update the duration of a MediaSource.
/// TODO defined errors when the MediaSource is closed and so on?
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaSourceDurationUpdateErrorCode {
    /// The `WaspHlsPlayer` had no MediaSource attached to its media element.
    NoMediaSourceAttached = 0,
    /// An unknown error arised
    UnknownError = 1,
}

impl MediaSourceDurationUpdateErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

/// Errors (or success) that can arise when attempting to "attach" a MediaSource to a media
/// element.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AttachMediaSourceErrorCode {
    /// Could not attach MediaSource to the media element because of an unknown error.
    UnknownError = 0,
    /// Could not attach MediaSource to the media element because no content is currently
    /// loaded.
    NoContentLoaded = 1,
}

impl AttachMediaSourceErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::UnknownError,
            1 => Self::NoContentLoaded,
            _ => Self::UnknownError,
        }
    }
}

/// Errors that can arise when calling the `jsRemoveBuffer` JavaScript function.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RemoveBufferErrorCode {
    /// The operation failed because the SourceBuffer instance linked to the given
    /// `SourceBufferId` was not found.
    SourceBufferNotFound = 0,
    /// The operation failed because of an unknown error.
    UnknownError = 1,
}

impl RemoveBufferErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::SourceBufferNotFound,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

/// Errors that can arise when calling the `jsEndOfStream` JavaScript function.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EndOfStreamErrorCode {
    /// The `WaspHlsPlayer` linked had no MediaSource attached to its media
    /// element.
    NoMediaSourceAttached = 0,
    /// The operation failed because of an unknown error.
    UnknownError = 1,
}

impl EndOfStreamErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

/// Error that might arise when parsing the Multivariant Playlist.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MultivariantPlaylistParsingErrorCode {
    /// The first line of the MultivariantPlaylist is not #EXTM3U.
    ///
    /// Are you sure this is a Multivariant Playlist?
    MissingExtM3uHeader = 0,
    /// The Multivariant Playlist has no variant.
    ///
    /// Are you sure this is a Multivariant Playlist and not a Media Playlist?
    MultivariantPlaylistWithoutVariant = 1,
    /// An `EXT-X-STREAM-INF` tag announced in the Multivariant Playlist,
    /// describing an HLS variant, had no URI associated to it. It should be
    /// mandatory.
    MissingUriLineAfterVariant = 2,
    /// An `EXT-X-STREAM-INF` tag announced in the Multivariant Playlist,
    /// describing an HLS variant, had an unreadable URI associated to it.
    UnableToReadVariantUri = 3,
    /// An `EXT-X-STREAM-INF` tag announced in the Multivariant Playlist,
    /// describing an HLS variant, had no `BANDWIDTH` attribute associated to it.
    /// It should be mandatory.
    VariantMissingBandwidth = 4,
    /// A value in the Multivariant Playlist was in an invalid format.
    InvalidValue = 5,
    /// An `EXT-X-MEDIA` tag announced in the Multivariant Playlist, describing
    /// an HLS variant, had no `TYPE` attribute associated to it. It should be
    /// mandatory.
    MediaTagMissingType = 6,
    /// An `EXT-X-MEDIA` tag announced in the Multivariant Playlist, describing
    /// an HLS variant, had no `NAME` attribute associated to it. It should be
    /// mandatory.
    MediaTagMissingName = 7,
    /// An `EXT-X-MEDIA` tag announced in the Multivariant Playlist, describing
    /// an HLS variant, had no `GROUP-ID` attribute associated to it. It should be
    /// mandatory.
    MediaTagMissingGroupId = 8,
    /// A line could not be read.
    UnableToReadLine = 9,
    /// Another, uncategorized, error arised.
    Unknown = 10,
}

impl MultivariantPlaylistParsingErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::MissingExtM3uHeader,
            1 => Self::MultivariantPlaylistWithoutVariant,
            2 => Self::MissingUriLineAfterVariant,
            3 => Self::UnableToReadVariantUri,
            4 => Self::VariantMissingBandwidth,
            5 => Self::InvalidValue,
            6 => Self::MediaTagMissingType,
            7 => Self::MediaTagMissingName,
            8 => Self::MediaTagMissingGroupId,
            9 => Self::UnableToReadLine,
            10 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

/// Error that might arise when parsing the Media Playlist.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaPlaylistParsingErrorCode {
    /// An `#EXTINF` tag announced in the Media Playlist was not in the right
    /// format.
    UnparsableExtInf = 0,
    /// An `#EXT-X-MAP` tag in the Media Playlist didn't its mandatory `URI`
    /// attribute.
    UriMissingInMap = 1,
    /// There was no `#EXT-X-TARGETDURATION` tag in the Media Playlist.
    MissingTargetDuration = 2,
    /// One of the URI found in the Media Playlist wasn't associated to any
    /// `#EXTINF` tag.
    UriWithoutExtInf = 3,
    /// A `#EXT-X-BYTERANGE` tag or a `BYTERANGE` attribute in the Media Playlist
    /// was not in the right format.
    UnparsableByteRange = 4,
    /// Another, uncategorized, error arised.
    Unknown = 5,
}

impl MediaPlaylistParsingErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::UnparsableExtInf,
            1 => Self::UriMissingInMap,
            2 => Self::MissingTargetDuration,
            3 => Self::UriWithoutExtInf,
            4 => Self::UnparsableByteRange,
            5 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

/// Error that might arise when adding a SourceBuffer through a MediaSource instance.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AddSourceBufferErrorCode {
    /// The `WaspHlsPlayer` linked to it had no MediaSource attached to its media
    /// element.
    NoMediaSourceAttached = 0,
    /// The `MediaSource` instance linked to this `WaspHlsPlayer` is in a "closed" state.
    MediaSourceIsClosed = 1,
    /// A `QuotaExceededError` was received while trying to add the `SourceBuffer`
    ///
    /// Such errors are often encountered when another SourceBuffer attached to the same
    /// MediaSource instance was already updated through a buffer operation.
    QuotaExceededError = 2,
    /// The given mime-type and codec combination is not supported
    TypeNotSupportedError = 3,
    /// The given mime-type and codec combination is empty
    EmptyMimeType = 4,
    /// An unknown error happened.
    UnknownError = 5,
}

impl AddSourceBufferErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoMediaSourceAttached,
            1 => Self::MediaSourceIsClosed,
            2 => Self::QuotaExceededError,
            3 => Self::TypeNotSupportedError,
            4 => Self::EmptyMimeType,
            5 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

/// Errors that can arise when calling the `jsAppendBuffer` JavaScript function.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SegmentParsingErrorCode {
    /// The operation failed because the resource to append was not found.
    ///
    /// This error is only returned for cases where the data to push resides in JavaScript's
    /// memory (as opposed to given by the WebAssembly code).
    NoResource = 0,
    /// The operation failed because the SourceBuffer instance linked to the
    /// given `SourceBufferId` was not found.
    NoSourceBuffer = 1,
    /// The operation failed at the transmuxing stage.
    TransmuxerError = 2,
    /// The operation failed because of an unknown error.
    UnknownError = 3,
}

impl SegmentParsingErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::NoResource,
            1 => Self::NoSourceBuffer,
            2 => Self::TransmuxerError,
            3 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

/// Errors that can arise after a SourceBuffer's `appendBuffer` call.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PushedSegmentErrorCode {
    /// We could not push the segment because the `SourceBuffer`'s buffer seems full.
    BufferFull = 0,
    /// We could not push the segment because of another, unknown error.
    UnknownError = 1,
}

impl PushedSegmentErrorCode {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::BufferFull,
            1 => Self::UnknownError,
            _ => Self::UnknownError,
        }
    }
}

/// Reason that triggered a `PlaybackObservation`
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaybackObservationReason {
    /// First observation given initially, not linked to any particular event.
    Init = 0,
    /// Observation sent right after a "seeked" event has been received on the
    /// HTMLMediaElement.
    Seeked = 1,
    /// Observation sent right after a "seeking" event has been received on the
    /// HTMLMediaElement.
    Seeking = 2,
    /// Observation sent right after an "ended" event has been received on the
    /// HTMLMediaElement.
    Ended = 3,
    /// Observation sent right after a the HTMLMediaElement's `readyState`
    /// attribute changed
    ReadyStateChanged = 4,
    /// Observation sent regularly, at a set interval without any event.
    RegularInterval = 5,
    /// Observation sent as an error has been received on the HTMLMediaElement.
    Error = 6,
}

impl PlaybackObservationReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Init,
            1 => Self::Seeked,
            2 => Self::Seeking,
            3 => Self::Ended,
            4 => Self::ReadyStateChanged,
            5 => Self::RegularInterval,
            6 => Self::Error,
            _ => Self::Error,
        }
    }
}

/// "Reason" associated to a timer started by the WaspHlsPlayer.
///
/// This can then help to identify what the timer was for once resolved.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TimerReason {
    /// The timer is linked to the MediaPlaylistRefresh's mechanism, meaning
    /// that the wanted MediaPlaylist may have to be reloaded.
    MediaPlaylistRefresh = 0,
    /// The timer is linked to a failed request that has to be retried.
    RetryRequest = 1,
}

impl TimerReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::MediaPlaylistRefresh,
            1 => Self::RetryRequest,
            _ => Self::MediaPlaylistRefresh,
        }
    }
}

/// Levels with which a log can be emitted.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LogLevel {
    /// Log level reserved for very important errors and highly unexpected events.
    Error = 0,
    /// Log level reserved for less important errors and unexpected events.
    Warn = 1,
    /// Log level reserved for important events
    Info = 2,
    /// Log level used when debugging. Small-ish yet impactful events should be logged with it.
    Debug = 3,
}

impl LogLevel {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Error,
            1 => Self::Warn,
            2 => Self::Info,
            3 => Self::Debug,
            _ => Self::Error,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaType {
    Audio = 0,
    Video = 1,
}

impl MediaType {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Audio,
            1 => Self::Video,
            _ => Self::Audio,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaylistNature {
    Event = 0,
    VoD = 1,
    Live = 2,
    Unknown = 3,
}

impl PlaylistNature {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Event,
            1 => Self::VoD,
            2 => Self::Live,
            3 => Self::Unknown,
            _ => Self::Unknown,
        }
    }
}

/// Identify the JavaScript `readyState` of a created `MediaSource` instance.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MediaSourceReadyState {
    /// Corresponds to the "closed" JavaScript MediaSource's `readyState`
    Closed = 0,
    /// Corresponds to the "ended" JavaScript MediaSource's `readyState`
    Ended = 1,
    /// Corresponds to the "open" JavaScript MediaSource's `readyState`
    Open = 2,
}

impl MediaSourceReadyState {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Closed,
            1 => Self::Ended,
            2 => Self::Open,
            _ => Self::Closed,
        }
    }
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum StartingPositionType {
    Absolute = 0,
    FromBeginning = 1,
    FromEnd = 2,
}

impl StartingPositionType {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Absolute,
            1 => Self::FromBeginning,
            2 => Self::FromEnd,
            _ => Self::Absolute,
        }
    }
}

/// Identify the event that lead to the `MediaObservation` being sent.
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaybackTickReason {
    /// This is the initial observation emitted, right after it was started.
    Init = 0,
    /// This designates MediaObservation sent after an interval without any
    /// of the other events.
    RegularInterval = 1,
    /// The HTMLMediaElement's "seeking" event has just been triggered
    Seeking = 2,
    /// The HTMLMediaElement's "seeked" event has just been triggered
    Seeked = 3,
    /// The HTMLMediaElement's "loadeddata" event has just been triggered
    LoadedData = 4,
    /// The HTMLMediaElement's "loadedmetadata" event has just been triggered
    LoadedMetadata = 5,
    /// The HTMLMediaElement's "canplay" event has just been triggered
    CanPlay = 6,
    /// The HTMLMediaElement's "canplaythrough" event has just been triggered
    CanPlayThrough = 7,
    /// The HTMLMediaElement's "ended" event has just been triggered
    Ended = 8,
    /// The HTMLMediaElement's "pause" event has just been triggered
    Pause = 9,
    /// The HTMLMediaElement's "play" event has just been triggered
    Play = 10,
    /// The HTMLMediaElement's "ratechange" event has just been triggered
    RateChange = 11,
    /// The HTMLMediaElement's "stalled" event has just been triggered
    Stalled = 12,
}

impl PlaybackTickReason {
    pub fn from_raw(value: u32) -> Self {
        match value {
            0 => Self::Init,
            1 => Self::RegularInterval,
            2 => Self::Seeking,
            3 => Self::Seeked,
            4 => Self::LoadedData,
            5 => Self::LoadedMetadata,
            6 => Self::CanPlay,
            7 => Self::CanPlayThrough,
            8 => Self::Ended,
            9 => Self::Pause,
            10 => Self::Play,
            11 => Self::RateChange,
            12 => Self::Stalled,
            _ => Self::Init,
        }
    }
}
