// This file is generated by scripts/generate_wasm_abi_bindings.mjs.
// Do not edit it manually.
#![allow(non_snake_case)]
use super::{RequestId, ResourceId, SourceBufferId, TimerId};
#[allow(clippy::too_many_arguments)]
#[link(wasm_import_module = "wasp")]
unsafe extern "C" {
    /// Abort a pending network request identified by its request id.
    pub(super) fn __js_func__abort_request(request_id: RequestId) -> u32;
    /// Create a SourceBuffer for the given media type and MIME type.
    pub(super) fn __js_func__add_source_buffer(
        media_type: u32,
        typ_ptr: *const u8,
        typ_len: u32,
        source_buffer_id_out: *mut u32,
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Report freshly parsed content metadata back to the host.
    pub(super) fn __js_func__announce_fetched_content(
        playlist_type: u32,
        variant_info_ptr: *const u32,
        variant_info_len: u32,
        audio_tracks_info_ptr: *const u32,
        audio_tracks_info_len: u32,
    );
    /// Report an audio or video track selection update to the host.
    pub(super) fn __js_func__announce_track_update(
        media_type: u32,
        track_id: u32,
        is_selected: u32,
    );
    /// Report that variant lock state changed.
    pub(super) fn __js_func__announce_variant_lock_status_change(variant_id: u32);
    /// Report the currently selected variant update.
    pub(super) fn __js_func__announce_variant_update(variant_id: u32);
    /// Append one media segment to a SourceBuffer.
    ///
    /// Notes:
    /// - The JS marshalling for this binding is intentionally still handwritten because the return payload is packed.
    pub(super) fn __js_func__append_buffer(
        source_buffer_id: SourceBufferId,
        segment_id: ResourceId,
        base_decode_time_start_hi: u32,
        base_decode_time_start_lo: u32,
        base_decode_time_start_timescale: u32,
        reset_transmuxer_state: u32,
        has_start_out: *mut u32,
        start_value_hi_out: *mut u32,
        start_value_lo_out: *mut u32,
        has_end_out: *mut u32,
        end_value_hi_out: *mut u32,
        end_value_lo_out: *mut u32,
        timescale: *mut u32,
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Create and attach a MediaSource to the host media element.
    pub(super) fn __js_func__attach_media_source(
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Cancel a timer previously started by wasm.
    pub(super) fn __js_func__clear_timer(id: TimerId);
    /// Copy resource bytes into wasm memory.
    ///
    /// Notes:
    /// - This shares the same host method as `__js_func__get_resource_len`; only the low-level ABI differs.
    pub(super) fn __js_func__copy_resource_data(
        id: ResourceId,
        dest_ptr: *mut u8,
        dest_len: u32,
    ) -> u32;
    /// Signal end-of-stream to the active MediaSource.
    pub(super) fn __js_func__end_of_stream(
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Start a network request from JavaScript.
    pub(super) fn __js_func__fetch(
        url_ptr: *const u8,
        url_len: u32,
        has_range_base: u32,
        range_base: usize,
        has_range_end: u32,
        range_end: usize,
        timeout: f64,
    ) -> RequestId;
    /// Flush pending host-side buffered state.
    pub(super) fn __js_func__flush();
    /// Release a JavaScript-side resource buffer.
    pub(super) fn __js_func__free_resource(resource_id: ResourceId) -> u32;
    /// Return a random floating-point value.
    pub(super) fn __js_func__get_random() -> f64;
    /// Return the byte length for a JavaScript-side resource buffer.
    ///
    /// Notes:
    /// - This shares the same host method as `__js_func__copy_resource_data`; only the low-level ABI differs.
    pub(super) fn __js_func__get_resource_len(id: ResourceId) -> i32;
    /// Inspect a segment resource to extract codec and MIME metadata.
    ///
    /// Notes:
    /// - The JS marshalling for this binding is intentionally still handwritten because the success payload is multi-field.
    pub(super) fn __js_func__inspect_segment(
        segment_id: ResourceId,
        media_type_out: *mut u32,
        parsed_mime_type_ptr_out: *mut u32,
        parsed_mime_type_len_out: *mut u32,
        codec_ptr_out: *mut u32,
        codec_len_out: *mut u32,
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Ask the host whether a MIME type is supported.
    pub(super) fn __js_func__is_type_supported(
        media_type: u32,
        typ_ptr: *const u8,
        typ_len: u32,
    ) -> i32;
    /// Send a log line to the host environment.
    pub(super) fn __js_func__log(log_level: u32, ptr: *const u8, len: u32);
    /// Remove buffered media data from a SourceBuffer.
    pub(super) fn __js_func__remove_buffer(
        source_buffer_id: SourceBufferId,
        start: f64,
        end: f64,
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Detach and clean up the current MediaSource.
    pub(super) fn __js_func__remove_media_source(
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Seek the media element to a new playback position.
    pub(super) fn __js_func__seek(position: f64);
    /// Emit a media-playlist parsing error to the host.
    pub(super) fn __js_func__send_media_playlist_parsing_error(
        fatal: u32,
        code: u32,
        media_type: u32,
        message_ptr: *const u8,
        message_len: u32,
    );
    /// Emit a media-playlist request error to the host.
    pub(super) fn __js_func__send_media_playlist_request_error(
        fatal: u32,
        url_ptr: *const u8,
        url_len: u32,
        reason: u32,
        media_type: u32,
        status: u32,
    );
    /// Emit a multivariant-playlist parsing error to the host.
    pub(super) fn __js_func__send_multivariant_playlist_parsing_error(
        fatal: u32,
        code: u32,
        message_ptr: *const u8,
        message_len: u32,
    );
    /// Emit a multivariant-playlist request error to the host.
    pub(super) fn __js_func__send_multivariant_playlist_request_error(
        fatal: u32,
        url_ptr: *const u8,
        url_len: u32,
        reason: u32,
        status: u32,
    );
    /// Emit a generic error to the host.
    pub(super) fn __js_func__send_other_error(
        fatal: u32,
        code: u32,
        message_ptr: *const u8,
        message_len: u32,
    );
    /// Emit a pushed-segment processing error to the host.
    pub(super) fn __js_func__send_pushed_segment_error(
        fatal: u32,
        code: u32,
        media_type: u32,
        message_ptr: *const u8,
        message_len: u32,
    );
    /// Emit a remove-buffer error to the host.
    pub(super) fn __js_func__send_remove_buffer_error(
        fatal: u32,
        media_type: u32,
        message_ptr: *const u8,
        message_len: u32,
    );
    /// Emit a segment parsing error to the host.
    pub(super) fn __js_func__send_segment_parsing_error(
        fatal: u32,
        code: u32,
        media_type: u32,
        message_ptr: *const u8,
        message_len: u32,
    );
    /// Emit a segment request error to the host.
    pub(super) fn __js_func__send_segment_request_error(
        fatal: u32,
        url_ptr: *const u8,
        url_len: u32,
        is_init: u32,
        media_type: u32,
        start_ptr: *const f64,
        duration_ptr: *const f64,
        reason: u32,
        status: u32,
    );
    /// Emit a SourceBuffer creation error to the host.
    pub(super) fn __js_func__send_source_buffer_creation_error(
        fatal: u32,
        code: u32,
        media_type: u32,
        message_ptr: *const u8,
        message_len: u32,
    );
    /// Update the media-time offset used by the host.
    pub(super) fn __js_func__set_media_offset(media_offset: f64);
    /// Update the current MediaSource duration.
    pub(super) fn __js_func__set_media_source_duration(
        duration: f64,
        err_code_out: *mut u32,
        err_desc_ptr_out: *mut u32,
        err_desc_len_out: *mut u32,
    ) -> u32;
    /// Update the playback rate on the media element.
    pub(super) fn __js_func__set_playback_rate(playback_rate: f64);
    /// Start periodic playback observation callbacks.
    pub(super) fn __js_func__start_observing_playback();
    /// Notify the host that rebuffering started.
    pub(super) fn __js_func__start_rebuffering();
    /// Stop periodic playback observation callbacks.
    pub(super) fn __js_func__stop_observing_playback();
    /// Notify the host that rebuffering stopped.
    pub(super) fn __js_func__stop_rebuffering();
    /// Start a host-side timer and return its identifier.
    pub(super) fn __js_func__timer(duration: f64, reason: u32) -> TimerId;
    /// Update content-level metadata exposed by the host.
    pub(super) fn __js_func__update_content_info(
        has_minimum_position: u32,
        minimum_position: f64,
        has_maximum_position: u32,
        maximum_position: f64,
        playlist_nat: u32,
        is_finalized: u32,
        uses_program_date_time: u32,
    );
}
