// This file is generated by scripts/generate_wasm_abi_enums.mjs.
// Do not edit it manually.

export const PlaylistType = Object.freeze({
  MultivariantPlaylist: 0,
  MediaPlaylist: 1,
} as const);
export type PlaylistType = (typeof PlaylistType)[keyof typeof PlaylistType];

export const OtherErrorCode = Object.freeze({
  NoSupportedVariant: 0,
  UnfoundLockedVariant: 1,
  MediaSourceAttachmentError: 2,
  Unknown: 3,
} as const);
export type OtherErrorCode =
  (typeof OtherErrorCode)[keyof typeof OtherErrorCode];

export const SourceBufferCreationErrorCode = Object.freeze({
  AlreadyCreatedWithSameType: 0,
  CantPlayType: 1,
  EmptyMimeType: 2,
  MediaSourceIsClosed: 3,
  NoMediaSourceAttached: 4,
  QuotaExceededError: 5,
  Unknown: 6,
} as const);
export type SourceBufferCreationErrorCode =
  (typeof SourceBufferCreationErrorCode)[keyof typeof SourceBufferCreationErrorCode];

export const RequestErrorReason = Object.freeze({
  Timeout: 0,
  Status: 1,
  Error: 2,
  Other: 3,
} as const);
export type RequestErrorReason =
  (typeof RequestErrorReason)[keyof typeof RequestErrorReason];

export const RemoveMediaSourceErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  UnknownError: 1,
} as const);
export type RemoveMediaSourceErrorCode =
  (typeof RemoveMediaSourceErrorCode)[keyof typeof RemoveMediaSourceErrorCode];

export const MediaSourceDurationUpdateErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  UnknownError: 1,
} as const);
export type MediaSourceDurationUpdateErrorCode =
  (typeof MediaSourceDurationUpdateErrorCode)[keyof typeof MediaSourceDurationUpdateErrorCode];

export const AttachMediaSourceErrorCode = Object.freeze({
  UnknownError: 0,
  NoContentLoaded: 1,
} as const);
export type AttachMediaSourceErrorCode =
  (typeof AttachMediaSourceErrorCode)[keyof typeof AttachMediaSourceErrorCode];

export const RemoveBufferErrorCode = Object.freeze({
  SourceBufferNotFound: 0,
  UnknownError: 1,
} as const);
export type RemoveBufferErrorCode =
  (typeof RemoveBufferErrorCode)[keyof typeof RemoveBufferErrorCode];

export const EndOfStreamErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  UnknownError: 1,
} as const);
export type EndOfStreamErrorCode =
  (typeof EndOfStreamErrorCode)[keyof typeof EndOfStreamErrorCode];

export const MultivariantPlaylistParsingErrorCode = Object.freeze({
  MissingExtM3uHeader: 0,
  MultivariantPlaylistWithoutVariant: 1,
  MissingUriLineAfterVariant: 2,
  UnableToReadVariantUri: 3,
  VariantMissingBandwidth: 4,
  InvalidValue: 5,
  MediaTagMissingType: 6,
  MediaTagMissingName: 7,
  MediaTagMissingGroupId: 8,
  UnableToReadLine: 9,
  Unknown: 10,
} as const);
export type MultivariantPlaylistParsingErrorCode =
  (typeof MultivariantPlaylistParsingErrorCode)[keyof typeof MultivariantPlaylistParsingErrorCode];

export const MediaPlaylistParsingErrorCode = Object.freeze({
  UnparsableExtInf: 0,
  UriMissingInMap: 1,
  MissingTargetDuration: 2,
  UriWithoutExtInf: 3,
  UnparsableByteRange: 4,
  Unknown: 5,
} as const);
export type MediaPlaylistParsingErrorCode =
  (typeof MediaPlaylistParsingErrorCode)[keyof typeof MediaPlaylistParsingErrorCode];

export const AddSourceBufferErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  MediaSourceIsClosed: 1,
  QuotaExceededError: 2,
  TypeNotSupportedError: 3,
  EmptyMimeType: 4,
  UnknownError: 5,
} as const);
export type AddSourceBufferErrorCode =
  (typeof AddSourceBufferErrorCode)[keyof typeof AddSourceBufferErrorCode];

export const SegmentParsingErrorCode = Object.freeze({
  NoResource: 0,
  NoSourceBuffer: 1,
  TransmuxerError: 2,
  UnknownError: 3,
} as const);
export type SegmentParsingErrorCode =
  (typeof SegmentParsingErrorCode)[keyof typeof SegmentParsingErrorCode];

export const PushedSegmentErrorCode = Object.freeze({
  BufferFull: 0,
  UnknownError: 1,
} as const);
export type PushedSegmentErrorCode =
  (typeof PushedSegmentErrorCode)[keyof typeof PushedSegmentErrorCode];

export const PlaybackObservationReason = Object.freeze({
  Init: 0,
  Seeked: 1,
  Seeking: 2,
  Ended: 3,
  ReadyStateChanged: 4,
  RegularInterval: 5,
  Error: 6,
} as const);
export type PlaybackObservationReason =
  (typeof PlaybackObservationReason)[keyof typeof PlaybackObservationReason];

export const TimerReason = Object.freeze({
  MediaPlaylistRefresh: 0,
  RetryRequest: 1,
} as const);
export type TimerReason = (typeof TimerReason)[keyof typeof TimerReason];

export const LogLevel = Object.freeze({
  Error: 0,
  Warn: 1,
  Info: 2,
  Debug: 3,
} as const);
export type LogLevel = (typeof LogLevel)[keyof typeof LogLevel];

export const MediaType = Object.freeze({
  Audio: 0,
  Video: 1,
} as const);
export type MediaType = (typeof MediaType)[keyof typeof MediaType];

export const PlaylistNature = Object.freeze({
  Event: 0,
  VoD: 1,
  Live: 2,
  Unknown: 3,
} as const);
export type PlaylistNature =
  (typeof PlaylistNature)[keyof typeof PlaylistNature];

export const MediaSourceReadyState = Object.freeze({
  Closed: 0,
  Ended: 1,
  Open: 2,
} as const);
export type MediaSourceReadyState =
  (typeof MediaSourceReadyState)[keyof typeof MediaSourceReadyState];

export const StartingPositionType = Object.freeze({
  Absolute: 0,
  FromBeginning: 1,
  FromEnd: 2,
} as const);
export type StartingPositionType =
  (typeof StartingPositionType)[keyof typeof StartingPositionType];

export const PlaybackTickReason = Object.freeze({
  Init: 0,
  RegularInterval: 1,
  Seeking: 2,
  Seeked: 3,
  LoadedData: 4,
  LoadedMetadata: 5,
  CanPlay: 6,
  CanPlayThrough: 7,
  Ended: 8,
  Pause: 9,
  Play: 10,
  RateChange: 11,
  Stalled: 12,
} as const);
export type PlaybackTickReason =
  (typeof PlaybackTickReason)[keyof typeof PlaybackTickReason];
