// This file is generated by scripts/generate_wasm_abi_enums.mjs.
// Do not edit it manually.
export const PlaylistType = Object.freeze({
  MultivariantPlaylist: 0,
  MediaPlaylist: 1,
});
export const OtherErrorCode = Object.freeze({
  NoSupportedVariant: 0,
  UnfoundLockedVariant: 1,
  MediaSourceAttachmentError: 2,
  Unknown: 3,
});
export const SourceBufferCreationErrorCode = Object.freeze({
  AlreadyCreatedWithSameType: 0,
  CantPlayType: 1,
  EmptyMimeType: 2,
  MediaSourceIsClosed: 3,
  NoMediaSourceAttached: 4,
  QuotaExceededError: 5,
  Unknown: 6,
});
export const RequestErrorReason = Object.freeze({
  Timeout: 0,
  Status: 1,
  Error: 2,
  Other: 3,
});
export const RemoveMediaSourceErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  UnknownError: 1,
});
export const MediaSourceDurationUpdateErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  UnknownError: 1,
});
export const AttachMediaSourceErrorCode = Object.freeze({
  UnknownError: 0,
  NoContentLoaded: 1,
});
export const RemoveBufferErrorCode = Object.freeze({
  SourceBufferNotFound: 0,
  UnknownError: 1,
});
export const EndOfStreamErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  UnknownError: 1,
});
export const MultivariantPlaylistParsingErrorCode = Object.freeze({
  MissingExtM3uHeader: 0,
  MultivariantPlaylistWithoutVariant: 1,
  MissingUriLineAfterVariant: 2,
  UnableToReadVariantUri: 3,
  VariantMissingBandwidth: 4,
  InvalidValue: 5,
  MediaTagMissingType: 6,
  MediaTagMissingName: 7,
  MediaTagMissingGroupId: 8,
  UnableToReadLine: 9,
  Unknown: 10,
});
export const MediaPlaylistParsingErrorCode = Object.freeze({
  UnparsableExtInf: 0,
  UriMissingInMap: 1,
  MissingTargetDuration: 2,
  UriWithoutExtInf: 3,
  UnparsableByteRange: 4,
  Unknown: 5,
});
export const AddSourceBufferErrorCode = Object.freeze({
  NoMediaSourceAttached: 0,
  MediaSourceIsClosed: 1,
  QuotaExceededError: 2,
  TypeNotSupportedError: 3,
  EmptyMimeType: 4,
  UnknownError: 5,
});
export const SegmentParsingErrorCode = Object.freeze({
  NoResource: 0,
  NoSourceBuffer: 1,
  TransmuxerError: 2,
  UnknownError: 3,
});
export const PushedSegmentErrorCode = Object.freeze({
  BufferFull: 0,
  UnknownError: 1,
});
export const PlaybackObservationReason = Object.freeze({
  Init: 0,
  Seeked: 1,
  Seeking: 2,
  Ended: 3,
  ReadyStateChanged: 4,
  RegularInterval: 5,
  Error: 6,
});
export const TimerReason = Object.freeze({
  MediaPlaylistRefresh: 0,
  RetryRequest: 1,
});
export const LogLevel = Object.freeze({
  Error: 0,
  Warn: 1,
  Info: 2,
  Debug: 3,
});
export const MediaType = Object.freeze({
  Audio: 0,
  Video: 1,
});
export const PlaylistNature = Object.freeze({
  Event: 0,
  VoD: 1,
  Live: 2,
  Unknown: 3,
});
export const MediaSourceReadyState = Object.freeze({
  Closed: 0,
  Ended: 1,
  Open: 2,
});
export const StartingPositionType = Object.freeze({
  Absolute: 0,
  FromBeginning: 1,
  FromEnd: 2,
});
export const PlaybackTickReason = Object.freeze({
  Init: 0,
  RegularInterval: 1,
  Seeking: 2,
  Seeked: 3,
  LoadedData: 4,
  LoadedMetadata: 5,
  CanPlay: 6,
  CanPlayThrough: 7,
  Ended: 8,
  Pause: 9,
  Play: 10,
  RateChange: 11,
  Stalled: 12,
});
