/**
 * ============= generate_wasm_abi_bindings =============
 *
 * Generates low-level Rust and TypeScript ABI signatures from
 * `src/wasm/abi/wasm-functions.jsonc`.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";
import readWasmAbiFunctionsManifest from "./utils/parse_wasm-functions_file.mjs";

if (process.argv.includes("--help") || process.argv.includes("-h")) {
  console.log(`Usage: node ./scripts/generate_wasm_abi_bindings.mjs

Generates:
  - src/rs-core/bindings/js_functions/raw_wasm.rs
  - src/rs-core/bindings/js_functions/raw_host.rs
  - src/wasm/js/generatedTypes.ts

from src/wasm/abi/wasm-functions.jsonc.`);
  process.exit(0);
}

const dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(dirname, "..");
const rawWasmOutputPath = path.join(
  rootDir,
  "src",
  "rs-core",
  "bindings",
  "js_functions",
  "raw_wasm.rs",
);
const rawHostOutputPath = path.join(
  rootDir,
  "src",
  "rs-core",
  "bindings",
  "js_functions",
  "raw_host.rs",
);
const tsOutputPath = path.join(
  rootDir,
  "src",
  "wasm",
  "js",
  "generatedTypes.ts",
);

const manifest = await readWasmAbiFunctionsManifest();
const imports = manifest.imports ?? [];
const exports = manifest.exports ?? [];

await mkdir(path.dirname(rawWasmOutputPath), { recursive: true });
await mkdir(path.dirname(rawHostOutputPath), { recursive: true });
await mkdir(path.dirname(tsOutputPath), { recursive: true });

await writeFile(rawWasmOutputPath, renderRustExterns(imports));
await writeFile(rawHostOutputPath, renderRustHostStubs(imports));
await writeFile(
  tsOutputPath,
  await prettier.format(renderTsInterfaces(imports, exports), {
    filepath: tsOutputPath,
  }),
);

function renderRustExterns(functions) {
  const aliasImports = collectRustAliases(functions);
  const blocks = [
    "// This file is generated by scripts/generate_wasm_abi_bindings.mjs.",
    "// Do not edit it manually.",
    "",
    "#![allow(non_snake_case)]",
    "",
    aliasImports.length === 0
      ? null
      : `use super::{${aliasImports.join(", ")}};`,
    "",
    "#[allow(clippy::too_many_arguments)]",
    '#[link(wasm_import_module = "wasp")]',
    'unsafe extern "C" {',
  ].filter(Boolean);

  for (const fn of functions) {
    blocks.push(...renderRustDoc(fn.doc, "    "));
    blocks.push(...renderRustSignature(fn, "extern"));
  }
  blocks.push("}");
  return `${blocks.join("\n").trimEnd()}\n`;
}

function renderRustHostStubs(functions) {
  const aliasImports = collectRustAliases(functions);
  const blocks = [
    "// This file is generated by scripts/generate_wasm_abi_bindings.mjs.",
    "// Do not edit it manually.",
    "",
    "#![allow(non_snake_case)]",
    "#![allow(clippy::too_many_arguments)]",
    "",
    aliasImports.length === 0
      ? null
      : `use super::{${aliasImports.join(", ")}};`,
    "",
    "fn non_wasm_binding_panic(binding_name: &str) -> ! {",
    '    panic!("WASM JS binding `{binding_name}` called on non-wasm target")',
    "}",
    "",
  ].filter(Boolean);

  for (const fn of functions) {
    blocks.push(...renderRustDoc(fn.doc));
    blocks.push(...renderRustSignature(fn, "host"));
    blocks.push(`    non_wasm_binding_panic("${fn.wasmSymbol}")`);
    blocks.push("}");
    blocks.push("");
  }
  return `${blocks.join("\n").trimEnd()}\n`;
}

function renderTsInterfaces(importsList, exportsList) {
  const enumImports = collectTsImports(importsList, exportsList);
  const helperImports = collectTsHelperImports(importsList);
  const blocks = [
    "// This file is generated by scripts/generate_wasm_abi_bindings.mjs.",
    "// Do not edit it manually.",
    "",
    enumImports.length === 0
      ? null
      : `import type { ${enumImports.join(", ")} } from "./enums.js";`,
    helperImports.length === 0
      ? null
      : `import type { ${helperImports.join(", ")} } from "./types.js";`,
    "",
    "export interface HostBindings {",
  ].filter(Boolean);

  for (const fn of dedupeHostBindingEntries(importsList)) {
    blocks.push(...renderTsDoc(fn.doc, "  "));
    blocks.push(
      `  ${fn.typescript.methodName}(${renderTsArgs(fn.typescript.args)}): ${fn.typescript.returnType};`,
    );
  }
  blocks.push("}");
  blocks.push("");
  blocks.push("export interface WaspWasmExports {");
  for (const entry of exportsList) {
    blocks.push(...renderTsDoc(entry.doc, "  "));
    if (entry.wasm.kind === "property") {
      blocks.push(`  readonly ${entry.wasmSymbol}: ${entry.wasm.type};`);
    } else {
      blocks.push(
        `  ${entry.wasmSymbol}(${renderTsArgs(entry.wasm.args)}): ${entry.wasm.returnType};`,
      );
    }
  }
  blocks.push("}");
  blocks.push("");
  return `${blocks.join("\n").trimEnd()}\n`;
}

function renderRustReturnType(type) {
  return type === "void" ? "" : ` -> ${type}`;
}

function renderRustSignature(fn, mode) {
  const args =
    mode === "host"
      ? fn.rust.args.map((arg) => `_${arg.name}: ${arg.type}`)
      : fn.rust.args.map((arg) => `${arg.name}: ${arg.type}`);
  const prefix =
    mode === "host"
      ? `pub(super) unsafe fn ${fn.wasmSymbol}`
      : `    pub(super) fn ${fn.wasmSymbol}`;
  const suffix =
    mode === "host"
      ? `${renderRustReturnType(fn.rust.returnType)} {`
      : `${renderRustReturnType(fn.rust.returnType)};`;
  const inline = `${prefix}(${args.join(", ")})${suffix}`;
  if (args.length <= 3 && inline.length <= 88) {
    return [inline];
  }
  const lines = [`${prefix}(`];
  for (const arg of args) {
    lines.push(`${mode === "host" ? "    " : "        "}${arg},`);
  }
  lines.push(`${mode === "host" ? "" : "    "})${suffix}`);
  return lines;
}

function renderRustDoc(doc, indent = "") {
  if (doc.length === 0) {
    return [];
  }
  return doc.map((line) =>
    line.length === 0 ? `${indent}///` : `${indent}/// ${line}`,
  );
}

function renderTsDoc(doc, indent = "") {
  if (doc.length === 0) {
    return [];
  }
  const out = [`${indent}/**`];
  for (const line of doc) {
    out.push(line.length === 0 ? `${indent} *` : `${indent} * ${line}`);
  }
  out.push(`${indent} */`);
  return out;
}

function renderTsArgs(args) {
  return args.map((arg) => `${arg.name}: ${arg.type}`).join(", ");
}

function collectRustAliases(functions) {
  const knownAliases = ["RequestId", "ResourceId", "SourceBufferId", "TimerId"];
  const found = new Set();
  for (const fn of functions) {
    for (const arg of fn.rust.args) {
      for (const alias of knownAliases) {
        if (containsTypeToken(arg.type, alias)) {
          found.add(alias);
        }
      }
    }
    if (fn.rust.returnType !== "void") {
      for (const alias of knownAliases) {
        if (containsTypeToken(fn.rust.returnType, alias)) {
          found.add(alias);
        }
      }
    }
  }
  return knownAliases.filter((alias) => found.has(alias));
}

function collectTsImports(importsList, exportsList) {
  const builtins = new Set([
    "ArrayBuffer",
    "ArrayBufferLike",
    "BigInt",
    "Boolean",
    "BufferSource",
    "Float32Array",
    "Float64Array",
    "Int32Array",
    "Number",
    "Promise",
    "RequestInfo",
    "Response",
    "String",
    "URL",
    "Uint32Array",
    "Uint8Array",
    "Memory",
    "WebAssembly",
  ]);
  const helperTypes = new Set([
    "AppendBufferValue",
    "HostResult",
    "InspectSegmentValue",
    "SegmentHints",
  ]);
  const found = new Set();
  for (const entry of [...importsList, ...exportsList]) {
    const signatures = [];
    if (entry.typescript != null) {
      signatures.push(
        ...entry.typescript.args.map((arg) => arg.type),
        entry.typescript.returnType,
      );
    }
    if (entry.wasm?.kind === "method") {
      signatures.push(
        ...entry.wasm.args.map((arg) => arg.type),
        entry.wasm.returnType,
      );
    } else if (entry.wasm?.kind === "property") {
      signatures.push(entry.wasm.type);
    }
    for (const signature of signatures) {
      for (const token of signature.match(/\b[A-Z][A-Za-z0-9_]*\b/g) ?? []) {
        if (!builtins.has(token) && !helperTypes.has(token)) {
          found.add(token);
        }
      }
    }
  }
  return [...found].sort();
}

function collectTsHelperImports(importsList) {
  const knownHelpers = [
    "AppendBufferValue",
    "HostResult",
    "InspectSegmentValue",
    "SegmentHints",
  ];
  const found = new Set();
  for (const entry of importsList) {
    const signatures = [
      ...entry.typescript.args.map((arg) => arg.type),
      entry.typescript.returnType,
    ];
    for (const signature of signatures) {
      for (const helper of knownHelpers) {
        if (containsTypeToken(signature, helper)) {
          found.add(helper);
        }
      }
    }
  }
  return knownHelpers.filter((helper) => found.has(helper));
}

function containsTypeToken(signature, token) {
  return new RegExp(`\\b${token}\\b`).test(signature);
}

function dedupeHostBindingEntries(importsList) {
  const seen = new Map();
  for (const entry of importsList) {
    const key = `${entry.typescript.methodName}(${renderTsArgs(entry.typescript.args)}):${entry.typescript.returnType}`;
    if (!seen.has(key)) {
      seen.set(key, entry);
    }
  }
  return [...seen.values()];
}
