// XXX TODO: Document script like others

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prettier from "prettier";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(dirname, "..");
const manifestPath = path.join(
  rootDir,
  "src",
  "wasm",
  "abi",
  "wasm-enums.json",
);
const rustOutputPath = path.join(
  rootDir,
  "src",
  "rs-core",
  "bindings",
  "abi_types.rs",
);
const tsOutputPath = path.join(
  rootDir,
  "src",
  "ts-common",
  "generatedWasmEnums.ts",
);

const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
const enums = Object.entries(manifest.enums);

function renderRust() {
  const blocks = [
    "// This file is generated by scripts/generate_wasm_abi_enums.mjs.",
    "// Do not edit it manually.",
    "",
  ];

  for (const [name, spec] of enums) {
    blocks.push("#[repr(u32)]");
    blocks.push("#[derive(Clone, Copy, Debug, PartialEq, Eq)]");
    blocks.push(`pub enum ${name} {`);
    for (const [member, value] of Object.entries(spec.members)) {
      blocks.push(`    ${member} = ${value},`);
    }
    blocks.push("}");
    blocks.push("");
    blocks.push(`impl ${name} {`);
    blocks.push("    pub fn from_raw(value: u32) -> Self {");
    blocks.push("        match value {");
    for (const [member, value] of Object.entries(spec.members)) {
      blocks.push(`            ${value} => Self::${member},`);
    }
    blocks.push(`            _ => Self::${spec.default},`);
    blocks.push("        }");
    blocks.push("    }");
    blocks.push("}");
    blocks.push("");
  }

  return `${blocks.join("\n").trimEnd()}\n`;
}

function renderTs() {
  const blocks = [
    "// This file is generated by scripts/generate_wasm_abi_enums.mjs.",
    "// Do not edit it manually.",
    "",
  ];

  for (const [name, spec] of enums) {
    blocks.push(`export const ${name} = Object.freeze({`);
    for (const [member, value] of Object.entries(spec.members)) {
      blocks.push(`  ${member}: ${value},`);
    }
    blocks.push("} as const);");
    blocks.push(`export type ${name} = (`);
    blocks.push(`  typeof ${name}`);
    blocks.push(`)[keyof typeof ${name}];`);
    blocks.push("");
  }

  return `${blocks.join("\n").trimEnd()}\n`;
}

await mkdir(path.dirname(rustOutputPath), { recursive: true });
await mkdir(path.dirname(tsOutputPath), { recursive: true });
await writeFile(rustOutputPath, renderRust());
await writeFile(
  tsOutputPath,
  await prettier.format(renderTs(), { filepath: tsOutputPath }),
);
